### ISSUE TITLE
how to output result to file?

### ISSUE THREAD

**Issue by sechacking** [xmendez/wfuzz#10]
how to output result to a file?

**Comment by xmendez** [comment]
This are the available output modes:

$ python wfuzz.py -e printers

Available printers:

  Name      | Description                         
--------------------------------------------------
  verbose   | Results in verbose format           
  default   | Default output format               
  html      | Prints results in html format       
  magictree | Prints results in magictree format  

Currently, there is no raw mode to output to a file. A new printer could be created for this.

**Comment by xmendez** [comment]
Added raw printer in order to output results into files easily. Commit 810fb0fb646e1d53cc918bf76e7768f0b3a10b1e
