### ISSUE TITLE
POST / PUT / PATCH requests with empty request body never "finish"

### ISSUE THREAD

**Issue by Prinzhorn** [xmendez/wfuzz#105]
```
wfuzz -z file,lists/path-prefix.txt -X POST http://localhost:8081/FUZZ
```

or

```
 wfuzz -z file,lists/path-prefix.txt -X POST -d "" http://localhost:8081/FUZZ
```

Will just "hang" and timeout eventually. However, the request is made correctly. This is what burp shows (but only after klling wfuzz. Without burp in between the server receives the request immediately but wfuzz doesn't end after getting the response).

```
POST / HTTP/1.1
Host: localhost:8081
Accept: */*
Content-Type: application/x-www-form-urlencoded
User-Agent: Wfuzz/2.3.1
Expect: 100-continue
Content-Length: 0
Connection: close


```

```
HTTP/1.1 100 Continue

HTTP/1.1 405 Method Not Allowed
server: ecstatic-3.1.1
Date: Mon, 17 Dec 2018 11:37:13 GMT
Connection: close
Content-Length: 0


```

**Comment by xmendez** [comment]
Hi,

Can you please provide the version that you are using?

cheers

**Comment by xmendez** [comment]
Ok, I will have a look later this afternoon.
Good point about the template.

Thanks!

**Comment by Prinzhorn** [comment]
Thanks!

As a workaround for now  I'm using `--slice "FUZZ!=''"` if I'm using a payload list that can contain unwanted empty lines (e.g. https://github.com/danielmiessler/SecLists/tree/master/Fuzzing). Saves a few requests anyway.
