### ISSUE TITLE
Can only run wfuzz from project's root folder

### ISSUE THREAD

**Issue by natemara** [xmendez/wfuzz#11]
It is impossible to run wfuzz from outside of the wfuzz root folder. If you follow these steps:

    $ git clone https://github.com/xmendez/wfuzz.git
    $ git reset --hard 574caa52be514ae012a0bdbb41350bd999c9dc9c
    $ python2 wfuzz/wfuzz.py
        /home/nate/.bin/wfuzz: 2: /home/nate/.bin/wfuzz: source: not found
    ********************************************************
    * Wfuzz 2.1.3 - The Web Bruteforcer                      *
    *                                                      *
    * Version up to 1.4c coded by:                         *
    * Christian Martorella (cmartorella@edge-security.com) *
    * Carlos del ojo (deepbit@gmail.com)                   *
    *                                                      *
    * Version 1.4d to 2.1.3 coded by:                        *
    * Xavier Mendez (xmendez@edge-security.com)            *
    ********************************************************

    Usage: /home/nate/.programs/wfuzz/wfuzz.py [options] -z payload,params <url>

    Type wfuzz.py -h for further information.

    Fatal exception: You must specify a payload and a URL
    No handlers could be found for logger "libraries.FileLoader"
    Traceback (most recent call last):
      File "/home/nate/.programs/wfuzz/wfuzz.py", line 52, in <module>
        Facade().sett.save()
      File "/home/nate/.programs/wfuzz/patterns/singleton.py", line 13, in __call__         
        class_.instance = super(Singleton, class_).__call__(*args, **kwargs)
      File "/home/nate/.programs/wfuzz/framework/core/facade.py", line 51, in __init__
        raise FuzzException(FuzzException.FATAL, "Error loading plugins: %s" % str(e))
    framework.core.myexception.FuzzException: Error loading plugins: No module named printers

**Comment by toby57** [comment]
sys.path.insert(0,"/usr/share/wfuzz_2.1/")
os.chdir("/usr/share/wfuzz_2.1/")

**Comment by xmendez** [comment]
Fixed on commit 95542a3e786c6aa8d0e5769d06e316df39c195dc
