### ISSUE TITLE
Only 403 response

### ISSUE THREAD

**Issue by adrylek** [xmendez/wfuzz#115]
Hello. First I'd like to thank you for the great help wfuzz has been. However, I'm having an issue I need to solve urgently.
When I fuzz a specific website, every response is 403. That sounds as if I might've gotten blacklisted, but that can't be the case, and I'm able to load the website perfectly on the browser. Do you know what could be causing this?

Thank you, and greetings from Barcelona.

**Comment by xmendez** [comment]
Hi,

It might be that they block based on the user agent?
Wfuzz uses wfuzz/2.3.3 as UA, you can change it in the command line or in the settings, check https://wfuzz.readthedocs.io/en/latest/user/advanced.html#wfuzz-global-options

Cheers

**Comment by adrylek** [comment]
> Hi,
> 
> It might be that they are blocking you based on the user agent?
> Wfuzz uses wfuzz/2.3.3 as UA, you can change it in the command line or in the settings, check https://wfuzz.readthedocs.io/en/latest/user/advanced.html#wfuzz-global-options
> 
> Cheers

Thank you so much! It has been driving me insane the entire day. Changing the user agent solved it. I'm wondering if there's an optimal one I should use now, or if any will be fine.

There's something else I've been meaning to post for a while. I have "--sc 200" in my command, as well as "-Z".
However, sometimes, when pycurl errors occur, they're listed out, when the documentation says that --sc 200 should filter out XXX responses as well. Is there something I can do to not list out those errors?
Thanks a lot again.

**Comment by xmendez** [comment]
Hi @adrylek,

No problem :)
About filtering XXX that should be due to wfuzz<2.4 not handling the term width correctly.

Cheers
