### ISSUE TITLE
wfuzz: configparser and python >3.5

### ISSUE THREAD

**Issue by blshkv** [xmendez/wfuzz#116]
Hello, 

wfuzz requires ```configparser``` however this package does not support python > 3.5.
Due to this, I'm facing the following error:
```
python3.6 /usr/bin/wfuzz 
Traceback (most recent call last):
  File "/usr/bin/wfuzz", line 86, in <module>
    exec(data, new_globals)
  File "<string>", line 11, in <module>
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2421, in load
    self.require(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 2444, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'configparser' distribution was not found and is required by the application
```

**Comment by xmendez** [comment]
If you are not using pip install wfuzz, you need to install the required dependencies by executing
pip3 install -r requierements.txt

**Comment by blshkv** [comment]
I do have configparser installed. And wfuzz does work with python2

**Comment by xmendez** [comment]
ConfigParser is not supported in python 3 but configparser is. What steps have you performed to install wfuzz?

**Comment by xmendez** [comment]
Thanks for the fix and please there is no need to be rude, it is only a label, that's it.

**Comment by blshkv** [comment]
sorry, I was not trying to be root. It was obvious (to me) that python3 provides ConfigParser so it has nothing to do with dependencies or my setup. I guess I'm just sick of talking to upstreams and hearing "did you run <the only tested way>? if not, we can't help".

**Comment by xmendez** [comment]
No worries. 
I've just merged the PR but looking at it again, should not configparser be installed only if python>3.0, python 2 should have ConfigParser already?

**Comment by blshkv** [comment]
I'm not a python expert, but from what I read, it's other way around :
'''
This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
'''

**Comment by blshkv** [comment]
Practically, configparser-3.5.0 supports python2 only (under Gentoo at least), so feel free to change it to something like:
```python_version=<"2.7" ```  (not tested). Meanwhile, my fix is good enough since the current stable version is 3.6 under gentoo.

Thanks!
