### ISSUE TITLE
Symbol # in url

### ISSUE THREAD

**Issue by aleixsb** [xmendez/wfuzz#12]
Hi!

I have the latest version wfuzz (2.1.3) available in kali linux. I'm trying to fuzz a website app that uses the symbol # to separate some vars, but it seems to cause some problem with wfuzz as it doesn't find the word FUZZ when it's behind this simbol.

Example:

This woks fine:
wfuzz -z file,/usr/share/wfuzz/wordlist/Injections/All_attack.txt --hc 404 https://example/FUZZ

But this is throwing a fatal exception:
wfuzz -z file,/usr/share/wfuzz/wordlist/Injections/All_attack.txt --hc 404 https://example/index.php#FUZZ

Fatal exception: FUZZ words and number of payloads do not match!

This was also happening in the version 2.0

I can do the fuzzing by replacing # with %23, but this shouldn't be happening right?

**Comment by toby57** [comment]
try this 
wfuzz -z file,/usr/share/wfuzz/wordlist/Injections/All_attack.txt --hc 404 "https://example/index.php#FUZZ"

**Comment by aleixsb** [comment]
It gives me the same error:

********************************************************
* Wfuzz 2.1.3 - The Web Bruteforcer                      *
********************************************************

Target: http://www.test.com/test/
Total requests: 468

==================================================================
ID	Response   Lines      Word         Chars          Request    
==================================================================


Fatal exception: FUZZ words and number of payloads do not match!

**Comment by xmendez** [comment]
When pycurl builds the HTTP requests ignores everything behind the #.
Encode the #, using %23 instead.

**Comment by crisofilaxx** [comment]
I'm trying to make this work from the command  line, but i was  unable, trying with or without quotes and the urlencoded # 
wfuzz -z file,/usr/share/wfuzz/wordlist/general/common.txt https://example.com/%23FUZZ
wfuzz -z file,/usr/share/wfuzz/wordlist/general/common.txt "https://example.com/%23FUZZ"
