### ISSUE TITLE
Any plans for creating Docker image ?

### ISSUE THREAD

**Issue by Chan9390** [xmendez/wfuzz#122]
## Context

This issue is more of a feature request. I had been working on Linux and recently moved to Mac. Installing wfuzz on Mac was a bit painful as the installation process is different than that in Linux. When I searched for any available docker images, I found that there are only 4 unofficial docker images that are not uptodate and doesnt work properly. 

Is there any plans for maintaining an official docker image ? (I could help if required)

**Comment by xmendez** [comment]
Hi,

Feel free to create a PR.

Cheers

**Comment by sandwich-destroyer** [comment]
bump..

**Comment by xmendez** [comment]
Now, you can use: 
docker pull ghcr.io/xmendez/wfuzz

cheers
