### ISSUE TITLE
Unhandled exception charmap

### ISSUE THREAD

**Issue by 0xskywalker** [xmendez/wfuzz#125]
Using the following syntax 

wfuzz -c -z file,/wordlist.txt - d parameter=FUZZ --hs Invalid http://address.com 

Produces an Unhandled exception: 'charmap' codec can't decide byte 0x8f in position 3159

**Comment by xmendez** [comment]
Hi, 

Is the wordlist that you're using public, so I can debug the issue?

Cheers

**Comment by 0xskywalker** [comment]
Yes. It's Kali Linux's rockyou.txt

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
