### ISSUE TITLE
Cannot POST data with Content-Type: application/json

### ISSUE THREAD

**Issue by manuelbua** [xmendez/wfuzz#127]
# Issue template

## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: `2.3.4`

Python version: `Python 2.7.16rc1`

OS: Kali Linux / Rolling, `4.19.20-1kali1 (2019-02-14) x86_64 GNU/Linux`

## Report

**What is the current behavior?**

Fuzzing JSON POST parameters will not work if a custom header for `Content-Type` is specified via `-H` switch, such as `Content-Type: application/json`, because no data, specified by the `-d` switch, will be POSTed at all.

**What is the expected or desired behavior?**

The specified data should be POSTed to the endpoint regardless of the specified custom `Content-Type` header.

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

The command line i'm using to reproduce the problem:
```bash
wfuzz -Z -c -t 1 -H "Content-Type: application/json" -z list,a-b-c -z list,1-2-3 -d '{"FUZZ":"FUZ2Z"}' -X POST -u "localhost:81/"
```
This is the output from the debug PHP script i'm using on the server side:
```
==========
2019-03-16 04:44:24
--> SERVER
Array
(
    [DOCUMENT_ROOT] => /tmp/1
    [REMOTE_ADDR] => 127.0.0.1
    [REMOTE_PORT] => 43352
    [SERVER_SOFTWARE] => PHP 7.3.2-3 Development Server
    [SERVER_PROTOCOL] => HTTP/1.1
    [SERVER_NAME] => 0.0.0.0
    [SERVER_PORT] => 81
    [REQUEST_URI] => /
    [REQUEST_METHOD] => POST
    [SCRIPT_NAME] => /index.php
    [SCRIPT_FILENAME] => /tmp/1/index.php
    [PHP_SELF] => /index.php
    [HTTP_HOST] => 81
    [HTTP_ACCEPT] => */*
    [CONTENT_TYPE] => application/json
    [HTTP_CONTENT_TYPE] => application/json
    [HTTP_USER_AGENT] => Wfuzz/2.2.9
    [HTTP_EXPECT] => 100-continue
    [REQUEST_TIME_FLOAT] => 1552751064.0285
    [REQUEST_TIME] => 1552751064
)

--> REQUEST
Array
(
)
--> REQUEST HEADERS
Array
(
    [Host] => 81
    [Accept] => */*
    [Content-Type] => application/json
    [User-Agent] => Wfuzz/2.2.9
    [Expect] => 100-continue
)
```

This is the PHP script used to debug POST data that dumps everything to `data.txt`:
```php
<?php
    if (!function_exists('getallheaders')) {
        function getallheaders() {
            $headers = [];
            foreach ($_SERVER as $name => $value) {
                if (substr($name, 0, 5) == 'HTTP_') {
                    $headers[str_replace(' ', '-', ucwords(strtolower(str_replace('_', ' ', substr($name, 5)))))] = $value;
                }
            }
            return $headers;
        }
    }

    $dump = "--> SERVER\n";
    $dump .= print_r($_SERVER, true);
    $dump .= "\n";
    $dump .= "--> REQUEST\n";
    $dump .= print_r($_REQUEST, true);
    $dump .= "--> REQUEST HEADERS\n";
    $dump .= print_r(getallheaders(), true);

    $date = new DateTime();
    $date = $date->format("Y-m-d h:i:s");
    $sep = "==========";
    file_put_contents("data.txt", $sep."\n".$date."\n".$dump."\n\n", FILE_APPEND);
?>
```

You can also notice the wrong UserAgent string from wfuzz `2.2.9`, just a minor thing.

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.

**Comment by manuelbua** [comment]
I can confirm this is issue is now resolved and JSON data can be posted, thanks for the fix @xmendez!

**Comment by maheshbasnet089** [comment]
wfuzz -d '{"email":"a@email.com","password":"FUZZ"}' --hc 405 -H 'Content-Type: application/
json' -z file,/home/hapihacker/rockyou.txt http://192.168.195.130:8888/api/v2/auth

Hope my syntax will guide you .
