### ISSUE TITLE
Unhandled exception: unknown encoding: CP-1251

### ISSUE THREAD

**Issue by heretic-m** [xmendez/wfuzz#128]
version 2.3.4
wfuzz -w base_dicw.txt --hc 404 http://example/FUZZ

**Comment by xmendez** [comment]
Hi,

This is same bug as #125. Wfuzz is not able to guess correctly the encoding of the wordlist file and crashes. I have been trying to improve this lately, if you have the chance, can you check if the dev branch handles the file correctly?

Cheers

**Comment by heretic-m** [comment]
Hi
It's about web page encoding, not about wordlist encoding.
Same issue exists when I try wordlist/general/big.txt
dev/master generate same exception

**Comment by xmendez** [comment]
Please, check if this issue has been addressed with Wfuzz 2.4.
