### ISSUE TITLE
wfuzz shouldn't store its configuration in the user home directory

### ISSUE THREAD

**Issue by nemoload** [xmendez/wfuzz#129]
According to the XDG Base Directory Specification user-specific configuration files should be stored at `$XDG_CONFIG_HOME` or `$HOME/.config`. 
See: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

https://github.com/xmendez/wfuzz/blob/bc67d05b435808de36315e385ef0e09422b2ebb0/src/wfuzz/facade.py#L15-L16

This line should be changed to something like:
```python
     def get_config_file(self): 
         return os.path.join(utils.get_config_dir(), "wfuzz.ini") 
```
If you're up to that I'd like to work on it just assign it to me.

**Comment by xmendez** [comment]
Hi @nemoload, happy if you create a PR for that change.

thanks

**Comment by nemoload** [comment]
I'm more than happy working on it.
