### ISSUE TITLE
Fatal exception: Error opening file

### ISSUE THREAD

**Issue by kevh35** [xmendez/wfuzz#13]
I have tried with tips of one website this :+1: 
python wfuzz.py -c -z file,wordliste/general/big.txt --hc 404 http://pentesterlab.com/FUZZ
and i get f:
Fatal exception: Error opening file

I'm on kali linux 2.0

**Comment by xmendez** [comment]
The wordlist/file you are trying to use is not in the specified path.

**Comment by Ekzorcist** [comment]
Hello, Xavier Mendez!
I have encountered the same bug.

root@debian:/usr/local/src/pentest/fuzz# ls -la
-rwxrwxrwx 1 root staff 224562 Oct 15 2015 raft-medium-directories-lowercase.txt

root@debian:/usr/local/src/pentest/fuzz# wfuzz -v -c -z file,raft-medium-directories-lowercase.txt --hh 765,845 http://m.site.com/FUZZ 
********************************************************
* Wfuzz 2.1.3 - The Web Bruteforcer *
* *
* Version up to 1.4c coded by: *
* Christian Martorella (cmartorella@edge-security.com) *
* Carlos del ojo (deepbit@gmail.com) *
* *
* Version 1.4d to 2.1.3 coded by: *
* Xavier Mendez (xmendez@edge-security.com) *
********************************************************

Usage: ./wfuzz.py [options] -z payload,params <url>

Type wfuzz.py -h for further information.


Fatal exception: Error opening file

How's that possible considering the fact that the file exists!
Do you have any idea on how to fix it ?
