### ISSUE TITLE
Fatal exception: FUZZ words and number of payloads do not match!

### ISSUE THREAD

**Issue by mehdi-desu** [xmendez/wfuzz#136]
so i'm trying brute force an http form in metasploitable DVWA app.

**here is my command:** 
`wfuzz -z file,users.txt -z file,wordlist.txt http://192.168.0.103/dvwa/vulnerabilities/brute/index.php?username=FUZZ&password=FUZ2Z&Login=Login`

**and here is the complete output :** 
```
Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz/plugins/payloads/bing.py Exception, msg=No module named shodan
libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz/plugins/payloads/shodanp.py Exception, msg=No module named shodan
********************************************************
* Wfuzz 2.4 - The Web Fuzzer                           *
********************************************************

Target: http://192.168.0.103/dvwa/vulnerabilities/brute/index.php?username=FUZZ
Total requests: 10

===================================================================
ID           Response   Lines    Word     Chars       Payload                                                                                     
===================================================================


Fatal exception: FUZZ words and number of payloads do not match!
```

**local environment:**

Wfuzz version: 2.4

Python version: Python 2.7.14+

OS: Kali Linux Rolling

## 

if you look at the Target url in the output you see that wfuzz is sending only the username parameter, i'm not sure why this is happening, but this explains the error message :   FUZZ words and number of payloads do not match.
Thanks!!

**Comment by xmendez** [comment]
Hi,Have you tried putting the URL between quotes? Bash might get confused with the &CheersOn 4 May 2019 21:00, mehdi-desu <notifications@github.com> wrote:so i'm trying brute force an http form in metasploitable DVWA app.
here is my command:
http://192.168.0.103/dvwa/vulnerabilities/brute/index.php?username=FUZZ&password=FUZ2Z&Login=Login#
and here is the complete output :
Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz/plugins/payloads/bing.py Exception, msg=No module named shodan
libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz/plugins/payloads/shodanp.py Exception, msg=No module named shodan
********************************************************
* Wfuzz 2.4 - The Web Fuzzer                           *
********************************************************

Target: http://192.168.0.103/dvwa/vulnerabilities/brute/index.php?username=FUZZ
Total requests: 10

===================================================================
ID           Response   Lines    Word     Chars       Payload                                                                                     
===================================================================


Fatal exception: FUZZ words and number of payloads do not match!

local environment:
Wfuzz version: 2.4
Python version: Python 2.7.14+
OS: Kali Linux Rolling

if you look at the Target url in the output you see that wfuzz is sending only the username parameter, i'm not sure why this is happening, but this explains the error message :   FUZZ words and number of payloads do not match.
Thanks!!

**Comment by mehdi-desu** [comment]
@xmendez , putting the URL between quotes solved the issue, thank you.
