### ISSUE TITLE
Error wfuzz

### ISSUE THREAD

**Issue by dzhenway** [xmendez/wfuzz#137]
C:\Python27\wfuzz-master>wfuzz
'wfuzz' is not recognized as an internal or external command,
operable program or batch file.

#############################

C:\Python27>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'PycURL/7.43.0.2 libcurl/7.60.0 OpenSSL/1.1.0h zlib/1.2.11 c-ares/1.14.0 WinIDN libssh2/1.8.0 nghttp2/1.32.0'
>>>

###################################

OS : Windows 10 Pro 64 Bit

**Comment by xmendez** [comment]
Hi,

You need to install wfuzz, using pip or setup.py. The wfuzz file in the main directory is only a shell script pointing to the python file.
