### ISSUE TITLE
Allow wfpayload to rewrite session with filtered results.

### ISSUE THREAD

**Issue by Shaddy** [xmendez/wfuzz#141]
It would be amazing (so far I didn't see a way to do it), to load a payload / session with wfpayload and rewrite its content. 

Let's say I did a session with a bunch of 404/400 results that I want to delete/skip. I could do --prefilter or similar before doing a query. But what I would like is to just curate my session without doing any request.

Thanks for your awesome job @xmendez !

**Comment by xmendez** [comment]
This has been done in dev version:
https://github.com/xmendez/wfuzz/commit/0e893cdaddd5da4bce8c87370bca49c1f9cc27e5
https://github.com/xmendez/wfuzz/commit/ab27a4126d60cd3c05b03dfabefed441239d6fa5
