### ISSUE TITLE
arielpresas@hotmail.com

### ISSUE THREAD

**Issue by pavigo** [xmendez/wfuzz#142]
# Issue template

## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version

Python version: Output of python --version

OS: X

## Report

**What is the current behavior?**

X

**What is the expected or desired behavior?**

X

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

X

**Other relevant information:**

X

**Comment by xmendez** [comment]
Closing as I don't see any error reported. Please, update the description with the relevant information.
