### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by xsuperbug** [xmendez/wfuzz#144]
I got an error like : Warning: Pycurl and/or libcurl version is old. CONNECT_TO option is missing. Wfuzz --ip option will not be available.

Pycurl version :

'PycURL/7.43.0 libcurl/7.47.0 OpenSSL/1.0.2g zlib/1.2.8 libidn/1.32 librtmp/2.3'

Wfuzz version: 2.4

Python version: 2.7.12, 3.5.2

OS: Ubuntu 16.04

**Comment by xmendez** [comment]
Hi,

You need a newer pycurl/libcurl version as the warning is stating. Please, let me know if the message is not clear enough.

Cheers
