### ISSUE TITLE
Pycurl Issue 

### ISSUE THREAD

**Issue by noob0x01** [xmendez/wfuzz#146]
Mohammads-MacBook-Pro:wfuzz-2.3.4 hi115h4d0w$ wfuzz -w wordlist/general/common.txt --hc 404 http://testphp.vulnweb.com/FUZZ

Fatal exception: pycurl: libcurl link-time ssl backend (none/other) is different from compile-time ssl backend (openssl). Wfuzz needs pycurl to run. Pycurl could be installed using the following command:

pip install pycurl
MacBook-Pro:wfuzz-2.3.4 hi115h4d0w$ pip install pycurl
Requirement already satisfied: pycurl in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (7.43.0.2)
MacBook-Pro:wfuzz-2.3.4 hi115h4d0w$

**Comment by xmendez** [comment]
Please check installation docs at https://wfuzz.readthedocs.io/en/latest/user/installation.html#pycurl-on-macos

**Comment by l3d43r** [comment]
Still Not working ~~~!!! no mater if we do what the installation docs says.!!
