### ISSUE TITLE
JSON body POST requests with -A: `unhandled exception: 'str' object has no attribute 'keys'`

### ISSUE THREAD

**Issue by dkasak** [xmendez/wfuzz#148]
## Context

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

Wfuzz version: 2.4
Python version: Python 3.7.3
OS: Arch Linux

## Report

Running 

```
wfuzz -A -X POST -z range,1-5 -c -H 'content-type:application/json' -d "FUZZ" 'https://SOMEURL/'
```
Throws an unhandled exception

```
Unhandled exception: 'str' object has no attribute 'keys'
```

**Other relevant information:**

Removing either the `-A` flag or the custom content-type makes the command succeed and issue requests as expected. Possibly related to #105.

**Comment by xmendez** [comment]
Can you please if this is fixed in version 2.4.1?

thanks

**Comment by dkasak** [comment]
Seems fixed. :+1:

**Comment by xmendez** [comment]
Great, thx
