### ISSUE TITLE
Posting nested JSON data will post a broken mix of json_encoded and dict's str() representation

### ISSUE THREAD

**Issue by manuelbua** [xmendez/wfuzz#151]
## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version
wfuzz 2.4

Python version: Output of python --version
Python 2.7.16

OS: Kali Linux Rolling (latest)

## Report

**What is the current behavior?**

Posting nested JSON data will actually post JSON-encoded data at the outer level, but Python dictionary's str repr encoded data at the inner level. For example:

Posting `-d '{"test": "me", "another": "1"}'` will send `{"test": "me", "another": "1"}` as expected.
Posting `-d '{"test":"me","another":1,"nested":{"this":2}}'` will wrongly send `{"test": "me", "another": "1", "nested": "{u'this': 2}"}`.

**What is the expected or desired behavior?**

Posting `-d '{"test":"me","another":1,"nested":{"this":2}}'` should actually send `{"test": "me", "another": "1", "nested": {"this": 2}}`.

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

`wfuzz -u <url> -H "Content-Type: application/json" -X POST -d <data>`

**Other relevant information:**

There is an hacky way around this, and switching the casing in `Application/json` is enough to have the `src/wfuzz/externals/reqresp/Request::setPostData` method to set the data as `_non_parsed_post`:

`wfuzz -u <url> -H "Content-Type: Application/json" -X POST -d <data>`

However, some picky webservers will actually look for the lowercase version only.

**Comment by darrynten** [comment]
Seeing this on 2.4 too, things get weird as soon as a FUZZ is nested inside another object

**Comment by xmendez** [comment]
Can you please if this is fixed in version 2.4.1?

thanks
