### ISSUE TITLE
Dump full request and full response

### ISSUE THREAD

**Issue by manuelbua** [xmendez/wfuzz#152]
# Issue template

## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version
2.4

Python version: Output of python --version
2.7.16

OS: Kali rolling

## Report

It seems there is no easy way to dump the full request and full response for each fuzz result.

I tried `--field` within the commandline or saving the results and parsing them with `wfpayload` but it seems that there is no way to select multiple output fields within expressions.

It doesn't look like i can use `wfuzz` as a library to load previous `FuzzResults` and dump everything i need: am i missing something?

Should i parse the saved gzipped output with pickle and work from there?

**Comment by xmendez** [comment]
Hi @manuelbua,

Apologies for the delay in getting back to you. I am interested in your use case if you are still there.
What were you trying to do?

cheers

**Comment by xmendez** [comment]
In dev version you can use --field/--efield several times. This version will be eventually released.
