### ISSUE TITLE
Load raw request from file

### ISSUE THREAD

**Issue by mrschyte** [xmendez/wfuzz#16]
Wfuzz should be able to load a raw request from a file and fuzz the parameters in it. This would make it easier to use in more complex scenarios.

**Comment by maaaaz** [comment]
I dig that issue :)

**Comment by xmendez** [comment]
Hi, 
Agree, added to the features to be developed in next releases. 
Cheers 
On 20 Jun 2016 9:22 pm, "Thomas D." <notifications@github.com> wrote:I dig that issue :)

**Comment by mrschyte** [comment]
Thank you. That's super neat :) 👍
