### ISSUE TITLE
Fatal exception: FUZZ words and number of payloads do not match!

### ISSUE THREAD

**Issue by anas20155** [xmendez/wfuzz#160]
root@kali-linuxxx:/usr/share/wordlists/wfuzz/others# wfuzz -c -z file,names.txt -z file,names.txt --sc 200 "http://192.168.1.1/cgi-bin/login.cgi."user=FUZZ&pass=FUZ2Z
[1] 4233
root@kali-linuxxx:/usr/share/wordlists/wfuzz/others# 
Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/lib/python3/dist-packages/wfuzz/plugins/payloads/bing.py Exception, msg=No module named 'shodan'
libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/lib/python3/dist-packages/wfuzz/plugins/payloads/shodanp.py Exception, msg=No module named 'shodan'
********************************************************
* Wfuzz 2.4 - The Web Fuzzer                           *
********************************************************

Target: http://192.168.1.1/cgi-bin/login.cgi.user=FUZZ
Total requests: 74097664

===================================================================
ID           Response   Lines    Word     Chars       Payload                  
===================================================================

Fatal exception: FUZZ words and number of payloads do not match!

**Comment by xmendez** [comment]
Hi @anas20155 ,

The way you are using " there is going to confuse bash and therefore wfuzz cli.

Cheers
