### ISSUE TITLE
Warning messages go to stdout instead of stderr

### ISSUE THREAD

**Issue by PaperTsar** [xmendez/wfuzz#163]
Warning messages go to stdout instead of stderr, which makes piping output (for example json) harder. This happens with the following warning (I expect it does with the rest too): 
> Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

**Comment by nemoload** [comment]
I tried to reproduce this bug by completely uninstalling pycurl and the error was sent to stderr as it supposed to be. The error was written using `warnings.warn()` which is used in the other pycurl warnings so it should give the same result. 

I think this issue should be closed.

**Comment by xmendez** [comment]
Closing, fixed at https://github.com/xmendez/wfuzz/commit/cdec50b4c06e429ff0866af9b8aa0d08b9c476b7
