### ISSUE TITLE
Feature: add support for parsing req/resp saved from Burp's proxy

### ISSUE THREAD

**Issue by PaperTsar** [xmendez/wfuzz#165]
### Description
Wfuzz does not support reading saved items from Burpsuite, neither burplog, nor burpstate payload type works.

**Save req/resp to file from Burp:** right click in Burpsuite's proxy tool on a request, select save item(s).

**Comment by xmendez** [comment]
Hi @PaperTsar, 

It is not possible to save the burpstate anymore, this has been superseded by sessions and not supported in wfuzz.

Have you tried burplog? What issues do you have?

Cheers

**Comment by PaperTsar** [comment]
Rightclicking on a request/response in Burp's Proxy tool, saving it (Save item) as out.burp and then trying to run, `wfuzz -z burplog,out.burp FUZZ` results in:

```
********************************************************
* Wfuzz 2.4.1 - The Web Fuzzer                         *
********************************************************

Target: FUZZ
Total requests: <<unknown>>

===================================================================
ID           Response   Lines    Word     Chars       Payload
===================================================================


Fatal exception: Empty dictionary! Please check payload or filter.
```

**Comment by xmendez** [comment]
To use burplog, you have to enable burp loggin in Project options -> Misc -> logging

Cheers

**Comment by PaperTsar** [comment]
I didn't know, thank you!:) Maybe this should be included in the wiki.
