### ISSUE TITLE
Ability to take a file containing a list of URL to iterate over

### ISSUE THREAD

**Issue by maaaaz** [xmendez/wfuzz#17]
Hello @xmendez,

It would be awesome if you could add a specific option in order to **take a file containing a list of URL and iterate over**. This feature is really missing when you have to assess a large list of Web apps, for instance on an internal network.
I'm thinking about something like:
```
$ python wfuzz.py -w wordlist/general/common.txt -i urllist.txt
```
with `urllist.txt` containing like:
```
http://url1/FUZZ
http://url2/FUZZ
...
http://urln/FUZZ
```

Do you think it would be easy to add this ? (sorry, haven't dug into the code yet...).

Cheers!

**Comment by laramies** [comment]
Hi @maaaaz  Have you tried with this:

python wfuzz.py -z file,urls.txt -z file,wordlist/general/common.txt  FUZZ/FUZ2Z

Hope it helps!

**Comment by maaaaz** [comment]
Thank you, it does exactly what I wanted :)
