### ISSUE TITLE
Improvement:  Folders + Files.

### ISSUE THREAD

**Issue by vulnz** [xmendez/wfuzz#186]
Good day.
Please think about improvement on such function:

we have 1.com/FUZZ and we found 200 as a folder.
Now we need to run 1.com/FUZZ/FUZZ1.FUZZ2
where Fuzz 1 and fuzz 2 are files. In this case for now we do not have ability to do it using tool without usage of python, right?

Also I suggest to make this function and same for recursive folders ( it is there) + this function.
Cheers.

**Comment by xmendez** [comment]
Hi @vulnz,

You can use recursion for folders, you have to use -R<recursion level> but this not fully cover your example for that I would suggest to save the first session and then work with the results. See https://wfuzz.readthedocs.io/en/latest/user/advanced.html#reutilising-previous-results.

For example: 

$ wfuzz -z list --zD static-xmldb-infodb -u http://www.webscantest.com/FUZZ/ --oF /tmp/session

$ wfuzz -z wfuzzp --zD /tmp/session --sc 200 -z list --zD php-asp -u FUZZ[url]index.FUZ2Z --field url

**Comment by vulnz** [comment]
thank you man. 
Is it possible to implement this feature?

**Comment by xmendez** [comment]
Hi @vulnz, it is quite difficult to cover all the recursion use cases, I'd suggest to use the saved sessions.
Happy merge any contribution in that front 

cheers
