### ISSUE TITLE
Can you use different fuzz dicts for different parameters?

### ISSUE THREAD

**Issue by HenryHoggard** [xmendez/wfuzz#195]
Is it possible to use different fuzz dictionaries for different parameters eg:

`http://test.com/page?arg1=FUZZ1&arg2=FUZZ2`
or 
`http://test.com/FUZZ1?arg1=FUZZ2`

Where FUZZ1 and FUZZ2 are using different input files as their source?

**Comment by xmendez** [comment]
Hi @HenryHoggard, 

Each FUZnZ word is replaced by its associated payload. Therefore, you can do:

`wfuzz -w dic1 -w dic2 http://test.com/FUZZ1?arg1=FUZZ2
`

Cheers
