### ISSUE TITLE
Possibility to filter requests by responsed HTML?

### ISSUE THREAD

**Issue by iocio005** [xmendez/wfuzz#197]
Is it possible to apply any filter to received responses in order to search if there is any difference between one of another?

I mean, imagine that you are fuzzing a Login by brute force.
Good and wrong tries, responses a 302 status code with everything the same. The unique difference between them is responsed HTML.

How can I be able to know which combination match with the succeded login, if the good and the bad one responses the same http header?

**Comment by xmendez** [comment]
Hi @iocio005,

The simplest way and if you know something that is returned in the content of a succesful login, is to use -ss.
See an example here https://wfuzz.readthedocs.io/en/latest/user/getting.html#regex-filters

Cheers
