### ISSUE TITLE
Wfuzz Exits After Fatal exception: Pycurl error 28: Connection timed out after 90000 milliseconds

### ISSUE THREAD

**Issue by bugbounty69** [xmendez/wfuzz#198]
# Issue template

## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: 2.4.6

Python version: 2.7.18

OS: Linux 

## Report

**What is the current behavior?**
 
I get this error :

Fatal exception: Pycurl error 28: Connection timed out after 90000 milliseconds

when i fuzz a website and a page times out and it stops wfuzz .
i already have tried setting --req-delay to more than 90 seconds but it's not possible is still gives the same error and even tried to set it to 0 for infinite seconds and it's still the same 

**What is the expected or desired behavior?**

To be able to fuzz without my program stopping if a page timed out after 90 seconds and be able to set the --req-delay for more than 90 seconds or set to 0 for infinite seconds 

**Please provide steps to reproduce, including exact wfuzz command executed and output:**
This is the command I ran : 

wfuzz -u http://x.x.x.x/FUZZFUZ2Z -t 1000 -w /usr/
share/wordlists/wfuzz/general/megabeast.txt -w /usr/share/wordlists/wfuzz/genera
l/extensions_common.txt  

**Other relevant information:**

**Comment by bugbounty69** [comment]
Thank you very much in advance and thank u again for such a great tool

**Comment by xmendez** [comment]
Hi @bugbounty69,

That error is a connection timeout, I'd say that the server is doing some rate limiting and banning your IP after some requests, moreover when you have -t 1000, which is quite aggressive. Are you getting a 429 or similar HTTP codes before that happening?

I am working in a better http library to be able to have more granularity on the number of requests per second, when to pause, etc...

But for now, I'd suggest you to use a combination of slowing down wfuzz, -Z, using different proxies, using a smaller dictionary....

Cheers

**Comment by bugbounty69** [comment]
Thank You for the swift response @xmendez . I'm not getting the said HTTP code or any of that nature just getting 404. and i still get the error even after using -t 1 , and i can still access the website, i found that this error happens after a page takes more than the CURLOPT_TIMEOUT time to respond according to this answer : 

https://stackoverflow.com/questions/21501159/curl-error-operation-timed-out

this is overcome in wfuzz by setting the --req-delay option but the problem is i can't set that option for more than 90 seconds or to 0 for infinite seconds , and i think a connection timing out shouldn't stop the fuzzing process but the pycurl exception should be handled and that connection stopped .

Again I thank you very much for a great tool , and i hope the new http library won't be too much of a hastle to you

**Comment by xmendez** [comment]
You might timing out in the connection phase?

        --conn-delay N            : Sets the maximum time in seconds the connection phase to the server to take (CURLOPT_CONNECTTIMEOUT). Default 90.

**Comment by xmendez** [comment]
"and i think a connection timing out shouldn't stop the fuzzing process but the pycurl exception should be handled and that connection stopped .". As mentioned before, you can use -Z to ignore errors.

**Comment by bugbounty69** [comment]
Thank you so much
