### ISSUE TITLE
wfuzz only fuzz the first url parameter

### ISSUE THREAD

**Issue by jimmyzhangau** [xmendez/wfuzz#203]
Hi,
I'm running buildin wfuzz in Kali 2020

Wfuzz version: Output of wfuzz --version
2.4
Python version: Output of python --version
2.7.17

The issue is that wfuzz truncate the second url parameter so it fails if I run following command:

# wfuzz -w numbers.txt  http://xxx/home.asp?action=delete&id=FUZZ
[1] 72381
root@kali:~/# 
Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

Fatal exception: You must specify at least a FUZZ word!

[1]+  Done                    wfuzz -w numbers.txt http://xxx/home.asp?action=delete
root@kali:~/#

**Comment by xmendez** [comment]
Hi,

The & makes the command run in the background as it a shell special character.
You should use enclose the url in double or single quotes.

cheers
