### ISSUE TITLE
Unsatisfiable dependency?

### ISSUE THREAD

**Issue by Shados** [xmendez/wfuzz#206]
https://github.com/xmendez/wfuzz/blob/f7bbca4e533f2c70fb0762aede138d5c5f70a2a0/setup.py#L24-L25

Pypi shows the latest pyparsing version as 2.4.7, so this dependency appears to be impossible to fulfill? poetry at the least cannot resolve it.

**Comment by xmendez** [comment]
Hi,

You are right that 2.4.7 is the latest release, pyparsing version 3.x are marked as beta, according to https://pypi.org/project/pyparsing/#history.

Those setup lines were trying to acommodate this:
https://github.com/pyparsing/pyparsing/wiki/Python-3-planning
"This will require those on Py3.0-3.4 to use the legacy 2.4.1 release."

Thanks
