### ISSUE TITLE
Exception, msg=No module named shodan

### ISSUE THREAD

**Issue by Thefreebee** [xmendez/wfuzz#211]
# Issue template

I am having a very hard time using wfuzz after many re-installations still no luck am testing one of the lines from basic usage guide of course i changed word list with one installed using right path

wfuzz -w wordlist/general/common.txt http://testphp.vulnweb.com/FUZZ.php

## Context

**Please check:**

- [yes ] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: 2.4.7

Python version: 2.7.18

OS: Kali Linux

## Report

What is the current behavior?**

libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz-2.4.7-py2.7.egg/wfuzz/plugins/payloads/shodanp.py Exception, msg=No module named shodan
libraries.FileLoader: CRITICAL __load_py_from_file. Filename: /usr/local/lib/python2.7/dist-packages/wfuzz-2.4.7-py2.7.egg/wfuzz/plugins/payloads/bing.py Exception, msg=No module named shodan

What is the expected or desired behavior?**

Run the fuzzing

Please provide steps to reproduce, including exact wfuzz command executed and output:**

wfuzz -w wordlist/general/common.txt http://testphp.vulnweb.com/FUZZ.php

I test more than 1 command from basic usage guide but none works am not sure what is the issue or how to solve it

**Comment by xmendez** [comment]
Hi @Thefreebee,

Those messages are about not having the shodan module installed although labelled CRITICAL  (about to be removed in future versions) wfuzz should run anyway.

The command that you're showing is correct. Are you getting any other messages?

cheers

**Comment by Thefreebee** [comment]
well wfuzz doesn't get cancelled after getting those message however it runs but i cannot see any other output like it trying the fuzzing i tried using the -v for verbose but the same it just shows the errors and nothing else but doesn't get terminated
