### ISSUE TITLE
setup.py: pytest should not be under install_requires

### ISSUE THREAD

**Issue by blshkv** [xmendez/wfuzz#215]
hello, 

the latest commit introduced pytest and this is a good thing. However, it should be specified in "install_requires" section.
It belongs to ```tests_require```:
https://docs.pytest.org/en/2.7.3/goodpractises.html
````
setup(
    #...,
    tests_require=['pytest'],
    cmdclass = {'test': PyTest},
    )
```

**Comment by xmendez** [comment]
Hi @blshkv,

Thanks for the feedback. Any chance that you can create a PR with the change you're proposing?

Cheers
