### ISSUE TITLE
Begging for a CSV output printer

### ISSUE THREAD

**Issue by maaaaz** [xmendez/wfuzz#22]
Hello,

I know I'm sure not to be the first asking for it but really, give us a `CSV output` printer.
For large engagements it is a pain to parse raw output or worse...the html one!

Cheers.

**Comment by xmendez** [comment]
I recently comitted 810fb0fb646e1d53cc918bf76e7768f0b3a10b1e which includes a raw printer. You can use that one for easy copy and paste. CSV printer should be really easy to develop modifying this one.

**Comment by xmendez** [comment]
Merged pull request from @Yoginski who added a CSV printer. Thanks!
