### ISSUE TITLE
Big keyword loading problem

### ISSUE THREAD

**Issue by serhattsnmz** [xmendez/wfuzz#229]
# Issue template

## Context

**Please check:**

- [x] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version:

Tested both versions
3.0.1 - 2.4.5

Python version: 3.7 - 3.8

## Report

When I use big keyword list such as rockyou.txt, it took really really long time to start.  
I've both used that on virtual machine ( Kali Linux - WSL ) and native Windows OS ( Win 10 ), and both systems were same. 

Is there any good way to make it faster ?

**Comment by xmendez** [comment]
Hi @serhattsnmz , 

The file payload has a parameter not to count the dictionary's words. If you disable that, you might resolve this issue.

Cheers

**Comment by serhattsnmz** [comment]
Hi @xmendez 

How can I do that ?

**Comment by xmendez** [comment]
Hi,

`$ ./wfuzz -z help --slice file
Name: file 0.2
Categories: default
Summary: Returns each word from a file.
Author: Carlos del Ojo,Christian Martorella,Adapted to newer versions Xavi Mendez (@xmendez)
Description:
   Returns the contents of a dictionary file line by line.
Parameters:
   + fn: Filename of a valid dictionary
   - count (= True): Indicates if the number of words in the file should be counted.
   - encoding (= Auto): Indicates the file encoding.
`

You can execute wfuzz as follows:

`./wfuzz -w /tmp/2 --zP count=False http://www.google.com/FUZZ`

cheers

**Comment by serhattsnmz** [comment]
Thanks @xmendez
