### ISSUE TITLE
No plugins found

### ISSUE THREAD

**Issue by kratos-is-alive** [xmendez/wfuzz#249]
Hi, 
Whenever I run wfuzz it says no plugin found, I checked the installation even reinstalled it correctly . 
Please let me know the solutions for this

**Comment by xmendez** [comment]
Hi @kratos-is-alive,

Can you copy paste the command you are executing? and the output?

cheers

**Comment by kratos-is-alive** [comment]
Hello I reinstalled it again 4th time and now it started working again! Still need to figure out why it was causing that issue , now its working fine.
