### ISSUE TITLE
[v2.2.9] Wfuzz says pycurl is missing, but pycurl is installed

### ISSUE THREAD

**Issue by shotgundebugging** [xmendez/wfuzz#251]
Hello,

After a recent `softwareupdate --all --install --force` and `brew upgrade` it seems that wfuzz is not working anymore.

```
Fatal exception: Wfuzz needs pycurl to run. Pycurl could be installed using the following command:
pip install pycurl
```

But pycurl is already installed

`Requirement already satisfied: pycurl in ./Library/Python/2.7/lib/python/site-packages (7.43.0.5)`

```
➜  ~  brew info wfuzz                                                                                                                                                                                        
sidaf/pentest/wfuzz: stable 2.2.9
https://github.com/xmendez/wfuzz
/usr/local/Cellar/wfuzz/2.2.9_1 (215 files, 1.7MB) *
  Built from source on 2020-12-03 at 19:53:24
From: https://github.com/sidaf/homebrew-pentest/blob/HEAD/wfuzz.rb
==> Dependencies
Required: curl ✔
```
Python 2.7.16
MacOS Catalina 10.15.7

**Comment by xmendez** [comment]
Hi,

Not sure about that brew repository but common installation problems in Mac are described here https://wfuzz.readthedocs.io/en/latest/user/installation.html#pycurl-on-macos

For example, I had to re-install pycurl after a brew update also explained at the end of the link above.

Cheers

**Comment by shotgundebugging** [comment]
Thanks @xmendez, I have tried those steps several times.
After more digging I'm suspecting it has to do with with the SSL implementation since pip is also acting up
`WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),)': /simple/pycurl/`
I resolved that by passing `--trusted-host`.

I checked the code but it seems that wfuzz disables pycurl's SSL verifications so that should have solved that issue?https://github.com/xmendez/wfuzz/blob/f3b407feb067564ded325ba9317ad89130ca630c/src/wfuzz/factories/reqresp_factory.py#L28-L29


```
>>> pycurl.version
'PycURL/7.43.0.5 libcurl/7.64.1 SecureTransport (LibreSSL/2.8.3) zlib/1.2.11 nghttp2/1.39.2'
```

**Comment by xmendez** [comment]
A bit lost, where are you getting that warning?

**Comment by shotgundebugging** [comment]
Sorry if I wasn't clear enough. I get that when running `pip install wfuzz` or any other package. So I'm suspecting there's a deeper issue with pycurl. I will close this since it's rather something more specific to my environment than related to `wfuzz`. Thanks for your time!
