### ISSUE TITLE
How can I fuzz both paths and headers?

### ISSUE THREAD

**Issue by yoonsch217** [xmendez/wfuzz#268]
# Issue template

## Context

**Please check:**

- [X] I've read the docs for [Wfuzz](http://wfuzz.readthedocs.io/)

**Please describe your local environment:**

Wfuzz version: Output of wfuzz --version
3.1.0

Python version: Output of python --version
Python 3.8.2

OS: X

## Report

**What is the current behavior?**

Document introduces a way to fuzz headers. (https://wfuzz.readthedocs.io/en/latest/user/basicusage.html#fuzzing-custom-headers)

What I want more is to fuzz both paths and headers.

Something like:

```
$ wfuzz -w path-input.txt -w header-input.txt -H "User-Agent: FUZZ" http://testphp.vulnweb.com/FUZZ
```

How can I achieve this?

**What is the expected or desired behavior?**

X

**Please provide steps to reproduce, including exact wfuzz command executed and output:**

X

**Other relevant information:**

X

**Comment by Internon** [comment]
Hi,

There is an advanced guide where you can find "FUZ2Z", I have not tested it yet but in theory it should work as you want with 2 wordlists.
Link of the advanced guide:
https://wfuzz.readthedocs.io/en/latest/user/advanced.html
