### ISSUE TITLE
Ignore option order

### ISSUE THREAD

**Issue by maaaaz** [xmendez/wfuzz#39]
Hello again,

It would be great if the option order could not be taken into account while specifying the target.
For instance, if:
* `$ python wfuzz.py -w url.txt -w wlist.txt FUZZ/blabla/FUZ2Z -o csv`  
could be **equivalent** to:  
* `$ python wfuzz.py -o csv -w url.txt -w wlist.txt FUZZ/blabla/FUZ2Z`

Cheers :)

**Comment by xmendez** [comment]
This is only possible if the URL is specified using another command line option, ie. -u FUZZ/blabla/FUZ2Z.

**Comment by xmendez** [comment]
Fixed in new 2.2.0 release.
