### ISSUE TITLE
How Brute Force Login Authentification

### ISSUE THREAD

**Issue by yogikristiawan1** [xmendez/wfuzz#44]
I want use wfuzz to try brute force website that have feature use HTTPS and Post data method. Can anyone help me how to write the codes?
I have try 
wfuzz.py -c -z list,admin -z list,book-password-abc --hc 400 -d "loginOp=login&username=FUZZ&password=FUZ2Z&client=preferred" "https://website.com"
*website.com not the real site
and all the output result C=000.
Are there any parameters I forgot write in the codes?

**Comment by Bladefidz** [comment]
Hi, @yogikristiawan1.
I have already tried your command for several times. I have found a little fix in your command without looked around in the source code. You only need to add a slash character (/) in last position of URL, so your command should be like this:

`wfuzz.py -c -z list,admin -z list,book-password-abc --hc 400 -d "loginOp=login&username=FUZZ&password=FUZ2Z&client=preferred" "https://website.com/"`

Maybe i will looked for source code and push for a little fix. Hope you enjoy your day!
:+1:
