### ISSUE TITLE
Request limiter

### ISSUE THREAD

**Issue by Luigyms** [xmendez/wfuzz#45]
Hello!

I would like to know if there is a way of limiting the amount or speed of the requests because when i try to use wfuzz in a website with SSL i'm getting a lot of 503 errors because the website has a limit on requests per second, i guess. This problem, for some reason, also seems to lead python to eat all of my RAM if i'm using a proxy and i am forced to shutdown.
I have been running wfuzz on a controlled group ever since.

I already use the software for a while but this issue is common and i would love to see it fixed. 
Thank you
👍

**Comment by xmendez** [comment]
Hi,

Is it not enough with:

```
$ wfuzz --help
...
-t N                        : Specify the number of concurrent connections (10 default)
-s N                        : Specify time delay between requests (0 default)
...
```

Cheers
