### ISSUE TITLE
Library call to fuzz methods

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#49]
Hi Xavi

How would be the equivalent call in the library to fuzz methods?

python wfuzz -z list,GET-HEAD-POST-TRACE-OPTIONS -X FUZZ http://testphp.vulnweb.com/

I am trying wfuzz.fuzz(url=http://testphp.vulnweb.com/,method=["GET","HEAD","POST","TRACE","OPTIONS"]) and it says that i need to specify a payload. In this case, i dont want to fuzz any parameter with payloads, i just want to test the methods

Thanks

**Comment by xmendez** [comment]
Hi,

You still need to use payloads and the FUZZ keyword when using the library. An easy way of getting payloads from python iterables is to use get_payload. You could do something like:

```
import wfuzz

for r in wfuzz.get_payload(["GET","HEAD","POST","TRACE","OPTIONS"]).fuzz(url='http://testphp.vulnweb.com/', method="FUZZ"):
        print r
```

**Comment by javixeneize** [comment]
Beautiful.Should this be included in the documentation? I think it is a good addition

Thanks!
