### ISSUE TITLE
Can't define headers containing commas

### ISSUE THREAD

**Issue by epinna** [xmendez/wfuzz#5]
Hello,

Adding an header containing commas, e.g. 

`./wfuzzy.py -H 'Accept-Language: da, en-gb;q=0.8, en;q=0.7' ...`

Fails on command line parsing because `,` is considered as header separator. Is there a way to bypass this issue? A nice fix could be to build the header list supporting the cumulative use of the `-H` option, e.g. `./wfuzzy.py -H 'Accept-Language: da, en-gb' -H 'Accept: text/plain; q=0.5, text/html'`. Argparse python library support this.

Thanks.

**Comment by xmendez** [comment]
Hi epinna,

Thanks for the feedback, I think it is a good idea. You can download a new release (https://github.com/xmendez/wfuzz/releases/tag/2.1.2) with this feature.
