### ISSUE TITLE
Code not returned in python when using method fuzzing

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#51]
Hi

I recently open #49 and you advised how to run the method fuzzer from the python library

When running it, i can see it works fine, but the response doesnt contain the error code (it is displayed as 000)

00973:  C=000     98 L       240 W         4636 Ch        "GET"
00974:  C=000      0 L         0 W            0 Ch        "HEAD"
00976:  C=000      4 L        23 W          178 Ch        "TRACE"
00977:  C=000      0 L         0 W            0 Ch        "OPTIONS"
00975:  C=000      4 L        23 W          178 Ch        "POST"

Thanks

**Comment by xmendez** [comment]
Hi,

I just made a quick new release (2.2.2) fixing some bugs.
I tried again and it seems to work, can you retest?

Cheers

**Comment by javixeneize** [comment]
This one is solved now. Is the json also solved?

I have also noticed that the printer option in the library doesnt work correctly. I will open another bug for that one

Thanks for the quick solution!
