### ISSUE TITLE
python3 compatibility?

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#55]
Hi

Does this work with python3?

Im having the following error

SyntaxError: Missing parentheses in call to 'print'

Thanks

**Comment by hlef** [comment]
No, wfuzz is not Python 3 compatible for now.

This is a big problem because Python 2 will be officially deprecated in 2 years, and won't be included in Debian's next release.

Is there any Python 3 port of wfuzz planned ?

**Comment by xmendez** [comment]
At some point in 2 years time I guess there should be but not in the very near future.

**Comment by jyn514** [comment]
This is working with python3 as far as I can tell. I am using wfuzz version `2.3`.
