### ISSUE TITLE
Not showing requests

### ISSUE THREAD

**Issue by sparkas** [xmendez/wfuzz#56]
Hello,

here's a command used:
wfuzz -c -v -z file,/usr/share/wordlists/wfuzz/Injections/SQL.txt -d "username=FUZZ&password=#" http://192.168.0.199:8008/unisxcudkqjydw/vulnbank/client/login.php

Results:

![selection_001](https://user-images.githubusercontent.com/22420746/30933346-014c893c-a3d3-11e7-9f72-7573759a1dce.png)

As you can see, requests are not shown.  Is it a mistake on my part, or a bug?

**Comment by xmendez** [comment]
Guessing that it is same problem as issue #35

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
