### ISSUE TITLE
Option to ignore ssl errors

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#57]
Hi

Im trying to run wfuzz against my own server where i have a self signed certificate. Im having an error from PyCurl when doing the handshake

Fatal exception: Pycurl error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:443 

Can a wfuzz parameter be added to avoid ssl verification?

Thanks

**Comment by xmendez** [comment]
Hi, 

There is no SSL verification. That's a problem with OpenSSL.

Cheers

**Comment by javixeneize** [comment]
Hi

what about using requests library? It would solve the problem I think

**Comment by xmendez** [comment]
Do you have pycurl compiled against gnults or openssl?

**Comment by javixeneize** [comment]
OpenSSL

**Comment by xmendez** [comment]
Can you show the result of pycurl.version ?

**Comment by javixeneize** [comment]
From pip freeze

pycurl==7.43.0

**Comment by javixeneize** [comment]
Another option i can use it importing the self signed certificate into my local computer. In which path should it be? I assume it will not be in the main javaVM keystore, isnt it?

Thanks

**Comment by xmendez** [comment]
Again, this is not a problem of certificates. Wfuzz does not care about TLS authentication. It is a problem of the underneath SSL library that you are using, gnuTLS is prone to problems such as the one you are describing. Please, check the SSL library that you are using:

# python
Python 2.7.11 (default, Jan 11 2016, 21:04:40)
[GCC 5.3.1 20160101] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycurl
>>> pycurl.version
'PycURL/7.21.5 libcurl/7.47.0 GnuTLS/3.4.8 zlib/1.2.8 libidn/1.32 libssh2/1.5.0 nghttp2/1.6.0 librtmp/2.3'
>>>

**Comment by javixeneize** [comment]
Hi

I have downgraded pycurl to 7.19.0 and it seems to work fine. Just in case somebody else has this problem

Thanks
