### ISSUE TITLE
Compatibility with windows 64 bits?

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#59]
Hi

I am trying to install wfuzz in windows 64 bits and i am facing problems with wconio library. Apparently this library is only available for 32 bits (http://newcenturycomputers.net/projects/wconio.html)

Has anybody managed to install this?

Thanks

**Comment by HuhMe9** [comment]
lol

**Comment by xmendez** [comment]
wfuzz>2.4 uses colorama, so this problem should be fixed.

Cheers
