### ISSUE TITLE
Response code 000

### ISSUE THREAD

**Issue by javixeneize** [xmendez/wfuzz#62]
Hi

Im sending request to a test application i have and for some reason, sometimes i have as response the error code 000

However, the response is 200 for the GET request, and 404 for the rest of them

See the example below

Have you seen this before? If you need any extra information, let me know

Thanks

==================================================================
ID	Response   Lines      Word         Chars          Payload    
==================================================================

00001:  C=000     98 L	     240 W	   4636 Ch	  "GET"
00002:  C=000      0 L	       0 W	      0 Ch	  "HEAD"
00003:  C=000      4 L	      23 W	    178 Ch	  "POST"
00004:  C=000      4 L	      23 W	    178 Ch	  "TRACE"
00005:  C=000      0 L	       0 W	      0 Ch	  "OPTIONS"

Total time: 0.083100
Processed Requests: 5
Filtered Requests: 5
Requests/sec.: 60.16841

**Comment by xmendez** [comment]
Hi, What version are you using? wfuzz --version

**Comment by javixeneize** [comment]
2.2.3

The funny thing is that this happens randomly

**Comment by xmendez** [comment]
Last version is 2.2.8, can you please update and recheck.

**Comment by javixeneize** [comment]
Same

********************************************************
* Wfuzz 2.2.8 - The Web Fuzzer                         *
********************************************************

Target:
Total requests: 5

==================================================================
ID	Response   Lines      Word         Chars          Payload    
==================================================================


[0K000005:  C=[0m000[0m      0 L	       0 W	      0 Ch	  "OPTIONS"[0m


[0K000001:  C=[0m000[0m     98 L	     240 W	   4636 Ch	  "GET"[0m


[0K000002:  C=[0m000[0m      0 L	       0 W	      0 Ch	  "HEAD"[0m


[0K000003:  C=[0m000[0m      4 L	      23 W	    178 Ch	  "POST"[0m


[0K000004:  C=[0m000[0m      4 L	      23 W	    178 Ch	  "TRACE"[0m

**Comment by xmendez** [comment]
It seems like a bug but I do not have any way to reproduce it without the full command execution and access to that testing app.

**Comment by javixeneize** [comment]
Hi

I just saw there are other issues raised about this problem

https://github.com/xmendez/wfuzz/issues/4
https://github.com/xmendez/wfuzz/issues/44
https://blog.techorganic.com/2015/01/04/pegasus-hacking-challenge/

I dont think any of those solutions work for me. 

The command im triggering is

 wfuzz -f tjson.json,json -z "list,GET-HEAD-POST-TRACE-OPTIONS" -X FUZZ http://localhost:8080

Unfortunately i cant give you access to this application as it is just a local tool. Is there any way to make it more verbose to see the responses?

**Comment by xmendez** [comment]
While I am debugging the issue, use http://localhost:8080/ instead of http://localhost:8080

**Comment by javixeneize** [comment]
I tried that solution but it didn’t work.

**Comment by javixeneize** [comment]
Hi

I just tried this now and it works fine now. Thanks!
