### ISSUE TITLE
Fatal exception: Pycurl error 28: Connection timed out after 90000 milliseconds

### ISSUE THREAD

**Issue by koxu1996** [xmendez/wfuzz#63]
Hello. Your tool is amazing, but I often get following error:
`Fatal exception: Pycurl error 28: Connection timed out after 90000 milliseconds`
What about adding option to retry connection if it fails?

**Comment by xmendez** [comment]
This is already done. Requests are retried several times. Change ~/wfuzz/wfuzz.ini if you want to increase it.

**Comment by xmendez** [comment]
By the way, You can use -Z if you want to continue scanning and not to stop on errors such as that.

**Comment by koxu1996** [comment]
This option is what I was looking for :+1 It is a pity that documentation does not mention about it.

**Comment by xmendez** [comment]
http://wfuzz.readthedocs.io/en/latest/user/advanced.html#scan-mode-ignore-errors-and-exceptions

**Comment by koxu1996** [comment]
I can see it now :)
