### ISSUE TITLE
Wfuzz ignores --sc

### ISSUE THREAD

**Issue by flagohuvelle** [xmendez/wfuzz#68]
Hi, I'm having an issue filtering the output of wfuzz. Running the following command:

`wfuzz -t 50 --sc 200 -w ../../wordlist/SecLists/Discovery/Web_Content/common.txt -w ../../wordlist/SecLists/Discovery/Web_Content/raft-small-extensions.txt https://10.10.10.65/FUZZFUZ2Z | tee wfuzzSec.log`

ends up printing all the requests with 404 codes on the screen.

I get the same behavior with --hc 404. It just prints everything.

This behavior only occurs when the size of the window isn't large enough to accommodate the entire line. When the window is large enough, this doesn't happen.
I saw a similar bug reported when changing the size of tmux, but this occurs even when leaving the window with a fixed size from the beginning (not changing anything)
Thanks!

**Comment by xmendez** [comment]
Hi, That's a known issue, it is a problem with the screen size and erasing lines, see #35.

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
