### ISSUE TITLE
Unable to install using pip on windows 7

### ISSUE THREAD

**Issue by gd2klf** [xmendez/wfuzz#70]
Error message is:
....\distutils\util.py", line 127, in convert_path raise ValueError("path '%s' cannot end with '/'" % pathname)

Python is 3.6.4 and pip is 
pip 9.0.1 from .....\python36\lib\site-packages (python 3.6)

**Comment by Reelix** [comment]
https://github.com/xmendez/wfuzz/issues/55

wfuzz only works on Python 2 - Not Python 3

**Comment by xmendez** [comment]
Closing. Wfuzz supports python3 now, and the aforementioned error was fixed in 2.2.11
