### ISSUE TITLE
No Urlencode

### ISSUE THREAD

**Issue by evilgash** [xmendez/wfuzz#74]
I was using wfuzz with -w and in my dic I had the following patterns

```
' '
'  '
'   '
```
when i was feeding it to wfuzz and lookig at the network traffic I saw that the spaces where urlencoded (%20). However, i needed to send spaces without urlencoding. Is this possible and if how?

Thx!

**Comment by xmendez** [comment]
Hi, There is an option in the wfuzz.ini about encoding spaces or notCheers On 2 Mar 2018 9:34 a.m., evilgash <notifications@github.com> wrote:I was using wfuzz with -w and in my dic I had the following patterns
' '
'  '
'   '

when i was feeding it to wfuzz and lookig at the network traffic I saw that the spaces where urlencoded (%20). However, i needed to send spaces without urlencoding. Is this possible and if how?
Thx!
