### ISSUE TITLE
FuzzSession.fuzz(): hangs with 'pycurl.error: cannot invoke setopt() - no curl handle'

### ISSUE THREAD

**Issue by octes** [xmendez/wfuzz#75]
Hi,
For a small project I am trying to use the wfuzz api, but for the life of me I can not figure out what I am doing wrong. Specifically I am wondering if I am using FuzzSession correctly or if I ran into a bug. 

I am trying to use the FuzzSession object [0] in my script, but whenever I call fuzz() the second time I get the error below. The script hangs indefinitely after the error was encountered. 

$ python2 script.py
```
00658:  C=403      9 L        24 W          219 Ch        "properties"
00043:  C=403      9 L        24 W          216 Ch        "WEB-INF"
Traceback (most recent call last):
  File "script.py", line 14, in <module>
    for r in s.fuzz(url=url, postdata='mode=FUZZ&json={}', payloads=[("range", dict(default="0-1000"))]):
  File "<SOME PATH>/venv/lib/python2.7/site-packages/wfuzz/options.py", line 203, in fuzz
    for f in self.fz:
  File "<SOME PATH>/venv/lib/python2.7/site-packages/wfuzz/core.py", line 265, in next
    raise res.exception
pycurl.error: cannot invoke setopt() - no curl handle
```

$ cat script.py
```
#!/usr/bin/env python2
# -*- coding: utf-8 -*-

import wfuzz

target = 'https://10.0.0.1'
proxy = [('10.0.0.2', '8080', 'HTML')]
s=wfuzz.FuzzSession(proxies=proxy, hc=[404])
url = "%s/FUZZ" % (target)
for r in s.fuzz(url=url, payloads=[("file",dict(fn="./data/wfuzz/wordlist/general/common.txt"))]):
    print r

url = "%s" % (target)
for r in s.fuzz(url=url, postdata='mode=FUZZ&json={}', payloads=[("range", dict(default="0-1000"))]):
    print r
```

$ cat requirements.txt
```
pycurl==7.43.0.1
pyparsing==2.2.0
wfuzz==2.2.9
```

[0] https://wfuzz.readthedocs.io/en/latest/library/guide.html#fuzzsession-object

**Comment by xmendez** [comment]
Hi,

That's a but with the http session handling. In the meantime, you can use the api like this:
`
with wfuzz.FuzzSession(proxies=proxy, hc=[404]) as s:
url = "%s/FUZZ" % (target)
for r in s.fuzz(url=url, payloads=[("file",dict(fn="./data/wfuzz/wordlist/general/common.txt"))]):
    print r

url = "%s" % (target)
for r in s.fuzz(url=url, postdata='mode=FUZZ&json={}', payloads=[("range", dict(default="0-1000"))]):
    print r
`

**Comment by octes** [comment]
Hi xmendez,
I am not sure if this issue is resolved from your end yet, but I went ahead and tested the new version anyway. The second call to fuzz() works now (building from the current bugs2.2.9), but there seems to be another issue. After the script finishes executing, it hangs indefinitely without error.

To kill the script I have to suspend it(using ctrl+z), kill <pid> and return it to foreground (i.e. something seems to catch SIGINT, which could be the fault of my script).

Let me know if you need me to test something specific.

Thanks,
octes

**Comment by xmendez** [comment]
Hi octes,
If you do not use a context manager, you have to close the session.
In your first example:
s.close()

Cheers

**Comment by octes** [comment]
@xmendez thanks for the hint
