### ISSUE TITLE
hello,my fuzz failure of filter rules

### ISSUE THREAD

**Issue by Jumbo-WJB** [xmendez/wfuzz#76]
#my command is
wfuzz -c -w wordlist.txt --hc 404,403,400 --hl 7,0 --hw 25 --hh 219 http://www.domain/FUZZ
but,404 page will still appear

`
wfuzz -c -w wordlist.txt --hc 404,403,400 --hl 7,0 --hw 25 --hh 219 http://www.domain/FUZZ

Warning: Pycurl is not compiled against Openssl. Wfuzz might not work correctly when fuzzing SSL sites. Check Wfuzz's documentation for more information.

********************************************************
* Wfuzz 2.2.9 - The Web Fuzzer                         *
********************************************************

Target: http://www.domain/FUZZ
Total requests: 22554

==================================================================
ID	Response   Lines      Word         Chars          Payload    
==================================================================

000005:  C=404      7 L	      25 W	    219 Ch	  "/cmseditor/membertouxiang/jsp/file_manager_json.
000011:  C=404      7 L	      25 W	    219 Ch	  "/cmseditor/youjiantoudi/jsp/file_manager_json.js
000016:  C=404      7 L	      25 W	    219 Ch	  "/en_opay/tenpay/b2c/aaaa/jsp/jsp/tenpay/index
000017:  C=404      7 L	      25 W	    219 Ch	  "/en_opay/tenpay/b2c/1111/jsp/jsp/tenpay/retur
`

**Comment by xmendez** [comment]
Hi,

There is a bug when the width of the shown line is bigger than the screen.
Can you confirm if this is the case?

cheers

**Comment by Jumbo-WJB** [comment]
yes.
If the dictionary starts with a /,(such as /aaaa) the rule does not take effect. If the dictionary does not start with /,(such as aaaa) the rule takes effect.

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
