### ISSUE TITLE
error scanning site with wrong name on cert

### ISSUE THREAD

**Issue by digininja** [xmendez/wfuzz#8]
I'm trying to scan a site which has a valid certificate but for a wrong name, i.e. not a self-signed cert, and I'm getting this error:

```
Fatal exception: Pycurl error 56: gnutls_handshake() warning: The server name sent was not recognized
```

I've done quite a bit of searching and not worked out how to fix it but will keep looking. If you want to try this, try scanning my site at https://digininja.org that will give you the cert for digi.ninja.

**Comment by xmendez** [comment]
Hi Robin, Any chances that you cannot tell me the website so I can debug the issue?Cheers                                                                                                                                                                                                                                                                                                                                                                                                                   From: Robin WoodSent: Wednesday, 9 September 2015 11:35To: xmendez/wfuzzReply To: xmendez/wfuzzSubject: [wfuzz] error scanning site with wrong name on cert (#8)I'm trying to scan a site which has a valid certificate but for a wrong name, i.e. not a self-signed cert, and I'm getting this error:

Fatal exception: Pycurl error 56: gnutls_handshake() warning: The server name sent was not recognized


I've done 

—Reply to this email directly or view it on GitHub.

**Comment by digininja** [comment]
Run it against my site:

```
# ./wfuzz.py -z file,/opt/tools/web/wfuzz/wordlist/general/big.txt --hc 404 https://digininja.org/FUZZ
********************************************************
* Wfuzz 2.1.3 - The Web Bruteforcer                      *
********************************************************

Target: https://digininja.org/FUZZ
Total requests: 3036

==================================================================
ID      Response   Lines      Word         Chars          Request
==================================================================


Fatal exception: Pycurl error 56: gnutls_handshake() warning: The server name sent was not recognized

None

**Comment by xmendez** [comment]
I believe that this error is because pycurl is using gnutls instead of openssl. Check the wiki, there is an article about how to compile python against openssl.

**Comment by digininja** [comment]
That fixed it.

I assume that I now manually have to keep an eye on pycurl and keep it up
to date myself, I'll have to remember that.

The instructions in the wiki are out-of-date for the versions of things,
may be worth mentioning that or changing the instructions so they become
more generic.
