### ISSUE TITLE
-R usage  - Fatal exception: FUZZ words and number of payloads do not match!

### ISSUE THREAD

**Issue by ahmedehane** [xmendez/wfuzz#94]
Hi,
I would like to use like following command, but when I put -R 3 it gives following error, I also tried -R 1 and -R 2 , the result is same:

./wfuzz.py -c -t 30 -z file,wordlist/general/common.txt -z file,wordlist/general/extensions_common_aspx.txt --hc 404,403,502,XXX,503,500 -R 3 --hw BBB http://www.example.com/FUZZ{notthere}FUZ2Z{notthere}

It's working withour -R , but I need to this one, I need wfuzz to go 3 level depth for identified directories with the same wordlists.

What's the wrong this command, is there anyone to help me?
Thanks 
Regards

**Comment by xmendez** [comment]
Hi,

What version are you using?

cheers
