### ISSUE TITLE
i can't use wordlist to fuzz HTTP Method

### ISSUE THREAD

**Issue by gh0stkey** [xmendez/wfuzz#95]
I use this command : `wfuzz -w method.txt -X FUZZ -d "test=test" URL`
method.txt content:
```
POST
GET
PUT
OPTIONS
```
run:
![](https://user-images.githubusercontent.com/24655118/47612550-cb54c200-dab7-11e8-8441-c02a24643150.png)
When wfuzz request with `put method`, it gets stuck.

**Comment by damnboy** [comment]
you can use burp capture the PUT request and see what is going on

**Comment by gh0stkey** [comment]
use burpsuite request with PUT method:
![](https://user-images.githubusercontent.com/24655118/47612766-2ee0ee80-dabc-11e8-8424-4f19accd5b2d.png)
Is well.But wfuzz not work.

**Comment by damnboy** [comment]
-p选项挂个代理抓包看

**Comment by gh0stkey** [comment]
哈哈 也不行哟

**Comment by gh0stkey** [comment]
it's fixed.
<img width="925" alt="0" src="https://user-images.githubusercontent.com/24655118/47764180-05fc6b80-dcff-11e8-9ee3-b30c756f08bd.png">
