### ISSUE TITLE
Use too long payload, unable to hide code.

### ISSUE THREAD

**Issue by gh0stkey** [xmendez/wfuzz#96]
Run command:
`wfuzz --hc 404 -z list,"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-aaa" -u http://127.0.0.1/FUZZ`
<img width="925" alt="0" src="https://user-images.githubusercontent.com/24655118/47764921-88d2f580-dd02-11e8-8255-7e87bb5141fa.png">
I want to hide "404" code , but wfuzz can't hide.
I found that as long as the length of payload is greater than or equal to 31, it will not hide code.
<img width="925" alt="1" src="https://user-images.githubusercontent.com/24655118/47765211-d69c2d80-dd03-11e8-8874-e7223a3c81b4.png">

**Comment by xmendez** [comment]
This is a known issue, is due to the width of the terminal and the way lines are hidden.

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
