### ISSUE TITLE
Is possible to request to an https?

### ISSUE THREAD

**Issue by ondrejlohnisky** [xmendez/wfuzz#98]
https throws me server response 400
I cant estabilish connection with server.

`
00347:  0.032s   C=400      0 L	      25 W	    249 Ch          nginx/1.12.2                                                        "266"
`
Do i need any certificates or cookies?

**Comment by ondrejlohnisky** [comment]
In wireshark i cant see any HTTPS or HTTP protocols but i see just TCP and TLSv1.2 so i think the connection is wrong.

**Comment by xmendez** [comment]
Hi,

Yes, it is possible to use HTTPs connections. 400 is normally due to the request being incorrect.
Can you specify the wfuzz command line (or api code) that throws that error?

Cheers

**Comment by ondrejlohnisky** [comment]
This is the command which i used:
`wfuzz -X POST -v -c -s 2 -z file,passwords.txt -d "{'username':'ondra.lohnisky@seznam.cz','password':'FUZZ'}" -b lps=.eJxNjlFrAjEQhP9KWLBPorkTsQSktBTF0vrSoqUvIXe3V0NziWxyHij-965atLAvM8w3swfQZaRap_CDHhTMxqvV4vNl8prPl0_v-Rf0_wd0YSltQB1AVBxeY9UXciKWYSdymd0LmSk5VpkU87cPODJaE0bO18ZFZLlFaoxHn0Alatkxhc64qOCZKjTGnl6IuPemGZR7Nm3UFdamdUm35K5FhKklf7Fgk9I2quHQhW_rB1f6op-Dx4eItLMlTpEX3N0Nnp7R3uixl8_4uq674ax5_4_klTMLx19EdWUH.DsPBBA.QPwjhSgdIj7oo_Zv58CrPRGdVRY -b __gfp_64b=zZOG.JiQrRE_5P5Sj5HNo.TYS_L2VLG2yJUXbv2jV0L.77 -b lsds="10XEPfmk_L_WTFPoJF-Lm7fztBAbeHTtkNEwt2g8hk0_bC62LCrGDUxGbr7rDk1O19aU0EDF1pcXl1bQV4bM2YzOH47GT8xOzkyOD==" https://login.szn.cz/api/v1/login
`

**Comment by ondrejlohnisky** [comment]
Yo i think my problem is in Content-type, I need to set content-type:application/json becouse i am posting json but i am not able to. I tried setting `-H "Content-type: application/json"`
but that didnt changed anything :/

My request looks like this: 
`
POST /api/v1/login HTTP/1.1
Host: login.domain.com
Accept: */*
Cookie: lps=.eJxNjUGLwjAQhf9KGNCTaNtFqgFZFKl7UC8ruLcQ2-kaTFOZpBYU__sOVlZhLt_je_NuoHJPpQr1CR1IyLJ08Z1-_UTJdjldL6YweBfUwVA4gryBKFjeYzEQUSq29UUkUTwR8USOxzKKxWqzgztXS0LPfqmtR8YzUqUdugAyUMOJPqiYH2meMV4VWOrGBtWQ_e8QhoZcF8ExhLOXo5Gtf40berw6XQ3za8fL2uHnS5895N7HvJdkfG3bvgrMfY90MTnOsNLG8v6TeaVL7n8nmF26.DsTFvQ.SC_dEYjK8IUskbPa2Zipej5J3ns; __gfp_64b=zZOG.JiQrRE_5P5Sj5HNo.TYS_L2VLG2yJUXbv2jV0L.77
Content-Type: application/x-www-form-urlencoded
User-Agent: Wfuzz/2.3
Content-Length: 217
Connection: close

{'username':'name@domain.com','password':'pass','remember':true,'auth_only':0,'service':'email','return_url':'https://login.domain.com/loginDone?return_url=https%3A%2F%2Fwww.domain.com%2F&service=email'}
`

but i need it to look like this:
`
POST /api/v1/login HTTP/1.1
Host: login.domain.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: application/json;q=0.9,*/*;q=0.8
Accept-Language: cs,sk;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: https://login.domain.com/bad-credentials?username=ondra.lohnisky%40domain.com
Content-type: application/json
Content-Length: 210
Connection: close
Cookie: lps=.eJxNjUGLwjAQhf9KGNCTaNtFqgFZFKl7UC8ruLcQ2-kaTFOZpBYU__sOVlZhLt_je_NuoHJPpQr1CR1IyLJ08Z1-_UTJdjldL6YweBfUwVA4gryBKFjeYzEQUSq29UUkUTwR8USOxzKKxWqzgztXS0LPfqmtR8YzUqUdugAyUMOJPqiYH2meMV4VWOrGBtWQ_e8QhoZcF8ExhLOXo5Gtf40berw6XQ3za8fL2uHnS5895N7HvJdkfG3bvgrMfY90MTnOsNLG8v6TeaVL7n8nmF26.DsTFvQ.SC_dEYjK8IUskbPa2Zipej5J3ns; __gfp_64b=zZOG.JiQrRE_5P5Sj5HNo.TYS_L2VLG2yJUXbv2jV0L.77

{"username":"name@domain.com","password":"pass","remember":true,"auth_only":0,"service":"email","return_url":"https://domain.comloginDone?return_url=https%3A%2F%2Fdomain.com%2F&service=email"}
`

**Comment by ondrejlohnisky** [comment]
Okay i have found The main problem.
The broblem is that i am not able to change content type with `-H "Content-type: application/json"`

**Comment by ondrejlohnisky** [comment]
I wasnt able to change content type with -H "Content-type: application/json" becouse i wasn't POSTing an json format...
this is correct:
-d "{\"username\":\"ondra.lohnisky@seznam.cz\",\"password\":\"FUZZ\"}"

**Comment by ondrejlohnisky** [comment]
Solved
!
