### ISSUE TITLE
Unhandled exception: 'utf-8' codec can't decode file 'big.txt'

### ISSUE THREAD

**Issue by jyn514** [xmendez/wfuzz#99]
```sh
$ wfuzz -w wordlist/general/big.txt localhost/FUZZ

Unhandled exception: 'utf-8' codec can't decode byte 0xf3 in position 717: invalid continuation byte
$ wfuzz --version
2.3
```

Note this is not the same as https://github.com/xmendez/wfuzz/issues/92, as this is using version 2.3 with unicode.

Solution:
```sh
iconv --from-code=ISO_8859-1 --to-code=utf8 wordlist/general/big.txt > tmp; mv tmp wordlist/general/big.txt
```

This also happens for `wordlist/general/medium.txt` and `wordlist/Injections/bad_chars.txt`, the solution is similar.

**Comment by xmendez** [comment]
Hopefully fixed in 2.3.1
